version: '3'
services:
    gateway:
        container_name: gateway
        image: activedev/adcloud_gateway:0.3-preview
        expose:
            - 8080
        ports:
            - 8080:8080
        network_mode: "host"
        logging:
            driver: json-file
    aclservice:
        container_name: aclservice
        image: activedev/adcloud_aclservice:0.3-preview
        expose:
            - 9001
        ports:
            - 9001:9001
        network_mode: "host"
        logging:
            driver: json-file
